name: ci

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14, ubuntu-24.04-arm ]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.1
          cache-dependency-path: "**/*.sum"

      - name: Install poetry
        run: pip install poetry

      - name: Build wheel
        run: poetry build --format wheel

      - name: Install test dependencies
        run: poetry install --no-root --only=dev

      - name: Install whl
        run: poetry run pip install $(python scripts/find_whl.py)

      - name: Run tests
        run: poetry run pytest

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python}}
          path: dist

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry

      - name: Build sdist
        run: poetry build --format sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: [ build, build_sdist ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@4
        with:
          name: dist
          path: dist

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Check distributions
        run: |
          ls -la dist

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
