name: ci

on:
  push:

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.13t"]
    steps:
      - uses: actions/checkout@v4      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.1

      - name: Install poetry
        run: pip install poetry

      - name: Build wheel
        run: poetry build

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python}}
          path: ./dist/*.whl
